name: Add CNAME file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Create CNAME file
        run: echo 'core-utils.js.org' > ./build/CNAME

      - name: Commit CNAME file
        run: |
          cd ./build
          git config --global user.email "siffffdoul@gmail.com"
          git config --global user.name "dev-pengi"
          git add CNAME
          git commit -m "Add CNAME file"
          git push origin gh-pages
